### PR TITLE
Hooks without magic ✨ 

### PR DESCRIPTION
**Pull request by jchavarri**
@cristianoc brought up how hooks would look like without using `Obj.magic` so I gave it a try.

While doing so, I thought we could consolidate the `(hook, element)` tuple into the `hook` type, so in this PR is defined it becomes

```reason
type hook('t) = Hook(element, 't);
```

In practice, hooks don't exist without the elements attached to them, so this change made sense. It also simplifies a bit the type definitions from `useState` and other hook functions.

I also changed the order an put `element` first so the types are more readable when needed (having the hooks types first complicated the signatures a bit).

The different hook types (state, reducer etc) become also variants:

```reason
  type state('s) =
    | State('s)
  and reducer('r) =
    | Reducer('r)
  and effect =
    | Effect
  and context('t) =
    | Context('t)
```

and then adding a hook just involves adding the types to the resulting tuples:

```reason
  let addHook = (newHook, Hook(element, h)) => Hook(element, (h, newHook));
  let addState = (~state as s) => addHook(State(s));
  let addEffect = element => addHook(Effect, element);
  let addReducer = (~reducer as r) => addHook(Reducer(r));
  let addContext = (~value as v) => addHook(Context(v));
  let elementToHook = x => Hook(x, ());
  let elementFromHook = (Hook(x, _)) => x;
```

@bryphe I didn't want to block #43 so creating a PR based on that branch to have a separate discussion. I think in balance I prefer this version without `Obj.magic` considering the implementation in #43 being a little bit of a pre-optimization, we can always change it back to `Obj.magic` without changing the public API, if that becomes an issue. Looking forward to your feedback! 😄

### CODE REVIEW

**Comment by jchavarri** [comment]
I don't know how to select a base branch that I own and still keep it as PR 😄  The changes are just the last commit: https://github.com/revery-ui/reason-reactify/pull/46/commits/544b2f8ef847102b6333e4328c80247f8d9db081

**Comment by bryphe** [comment]
Excellent refactoring!  This is an improvement for both the readability of the code, as well as readability of the errors - and nice to not need `Obj.magic`. It seems really straightforward to add a new strongly-typed hook 'primitive' too in this framework. I like how clear and concise the typing logic in `addState`, `addEffect`, etc is now with the `addHook` method. Thanks @cristanoc for the help.

> I think in balance I prefer this version without Obj.magic considering the implementation in #43 being a little bit of a pre-optimization, we can always change it back to Obj.magic without changing the public API, if that becomes an issue. 

Agreed, I prefer this version too. I didn't have an idea how to do this _without_ `Obj.magic` but now it seems simple with the changes to the types. Once we have benchmarks in place, we can always revisit and revert back if this is a hot-path - but I suspect the bottlenecks will be in other places anyways.

It's a pleasure reading these PRs, as I'm continually learning more about the type system.

Since #43 is in, I think this just needs the last commit rebased or cherry-picked onto `master` - and then good to go 👍

**Review by bryphe — APPROVED** [review]
Looks great!

**Comment by jchavarri** [comment]
Thanks @bryphe ! I merged `master` in and tests look good. Merging then! 🚀

**Pull request merged**
